Blog/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from .import views
from .views import *
from django.urls import path 
from django.contrib.auth.decorators import login_required
app_name = 'blogs'
urlpatterns = [
    
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),

    path('', views.post, name='post'),
    # path('footer/', views.footerDisplay, name='footer'),
    path('about/', views.about, name='about'),
    path('post_detil/<str:pk>/', views.post_detil, name='post_detil'),
    path('update_detil/<str:pk>/', views.updatecomment, name='update_detil'),
    path('comment_reply/<str:pk>/', views.replycomment, name='comment_reply'),
    path('delete_comment/<str:pk>/', views.deletecomment, name='delete_comment'),
    path('delete_reply/<str:pk>/', views.deletereply, name='delete_reply'),
    path('update_reply/<str:pk>/', views.updatereply, name='update_reply'),
    # Help section urls
    path('Edu-help/', views.roomMate, name='Edu-help'),
    path('Edu-help-del/<str:pk>/', views.roommateDelete, name='Edu-help-del'),
    path('Edu-help-edit/<str:pk>/', views.editroommatePost, name='Edu-help-edit'),
    # Advertisment Urls
    path('carousel/', views.carousel, name='carousel'),

    # class based classes url
    # path('products/', MarketListView.as_view(), name='products'),
    path('products/', MarkeTemplateView.as_view(), name='products'),
    path('products/<int:pk>/', MarketUpdateview.as_view(),  name='products'),
    path('del-products/<int:pk>/', Marketdeleteview.as_view(),  name='del-products'),
    path('product/<int:pk>/', MarketDetailView.as_view(), name='product-detail'), 
    path('buy-form/', MarketCreationForm.as_view(),  name='buy-form'),  
    # path('buy-form/', views.MarketCreationForm, name='buy-form'), 
    

 ]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.



class Article(models.Model):
	reporter=models.ForeignKey(User, on_delete=models.CASCADE , blank=True , null=True)
	pub_date=models.DateTimeField()
	headline=models.CharField(max_length=200)
	slug=models.CharField(max_length=200)
	content=models.TextField()
	institution_name=models.CharField(max_length=100)
	institution_website=models.CharField(max_length=100)
	institution_acronmy=models.CharField(max_length=20)
	post_image=models.ImageField(null=True, blank=True,upload_to='Post-img/', default="er.jpg")


	@property
	def image_url(self):
		if self.post_image and hasattr(self.post_image,'url'):
			return self.post_image.url
		return None

	def __str__ (self):
		return self.headline



  
class Comment(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE)
	body=models.TextField()
	detil=models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
	comment_image=models.ImageField(null=True, blank=True, upload_to='comment-img/')

	@property
	def image_url(self):
		if self.comment_image and hasattr(self.comment_image,'url'):
			return self.comment_image.url
		return None
	
	
	def __str__(self):
		return self.body

class CommentReply(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE)
	body=models.TextField()
	detil=models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='reply')
	
	
	def __str__(self):
		return self.body

# Edublog help section
class RoommateHelp (models.Model):
	user=models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
	message=models.TextField()
	created=models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return self.message

class Carousel (models.Model):
	image=models.ImageField(upload_to="img")
	title=models.CharField(max_length=100)
	body=models.TextField()
	def __str__(self):
		return self.title

category_choices=[
	('Automobile', 'Automobile'),
	('Computer', 'Computer'),
	('Phone', 'Phone'),
	('Others', 'Others'),
]

class Market(models.Model):

	user =models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
	category=models.CharField(max_length=10, choices=category_choices)
	product_name=models.CharField(max_length=100)
	product_price=models.FloatField(default=10.00)
	post=models.DateTimeField(auto_now_add=True)
	product_image=models.FileField(null=True, blank=True, default='default-img.png', upload_to='comment-img/')
	contact_details=models.IntegerField(null=True, blank=True)

	@property
	def image_url(self):
		if self.product_image and hasattr(self.product_image, 'url'):
			return self.product_image
		return None

	def __str__(self):
	 	return self.category


	# def get_absolute_url(self):

	# 	return reverse('products')

blogs/forms.py
from django import forms
from .models import Comment,CommentReply, RoommateHelp , Market


class CommentForm(forms.ModelForm):
	# user= forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class':'form-control', 'Placeholder':'Enter Username' }))
	body=forms.CharField(max_length=100, widget=forms.Textarea(attrs={'class':'form-control','Placeholder':'Login to drop a comment here....','rows':3}))
	class Meta:
		model=Comment
		comment_image= forms.ImageField(required=False)
		fields=[ 'body','comment_image']
		
class ReplyForm(forms.ModelForm):
	# user= forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class':'form-control', 'Placeholder':'Enter Username' }))
	body=forms.CharField(max_length=100, widget=forms.Textarea(attrs={'class':'form-control','Placeholder':'Enter reply here...','rows':3}))
	class Meta:
		model=CommentReply
		fields=[ 'body']
		
class RoommateHelpForm(forms.ModelForm):
	message=forms.CharField(max_length=1000, widget=forms.Textarea(attrs={'class':'form-control','Placeholder':'Enter Enter message here...','rows':3}))
	class Meta:
		model=RoommateHelp
		fields=['message',]


class ContactForm(forms.Form):

	message=forms.CharField(max_length=1000, widget=forms.Textarea(attrs={'class':'form-control','Placeholder':'Enter Enter message here...','rows':3}))

class SellForm(forms.ModelForm):
	class Meta:

		model=Market
		fields= ['category', 'product_name', 'product_price', 'product_image', 'contact_details']

		

blogs/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from django.urls import reverse
from .models import *
from .forms import CommentForm, ReplyForm, RoommateHelpForm, ContactForm, SellForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.forms  import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages
from django.contrib.messages import get_messages
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import ListView,DetailView, TemplateView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin
import re
# Create your views here.



def loginPage(request):
	page='login'
	#Prevent the user from accessing the login page when the are already logged in
	if request.user.is_authenticated:
		return redirect('blogs:post')

	if request.method=='POST':
		username=request.POST.get('username')
		password=request.POST.get('password')
		try:
			user=User.objects.get(username=username)
		except:
			messages.error(request, 'User does not exits')

		user=authenticate(request, username= username, password=password)
		
		if user is not None:
			login(request, user)
			return redirect('blogs:post')
		else:

			messages.error(request, 'Username or password incorrect')

	context={'page':page}
	return render(request, 'blogs/login_register.html',context)


def logoutUser(request):
	logout(request)
	# return render(request, 'blogs/index.html')
	return redirect ("blogs:post")
 

def registerPage(request):
	form=UserCreationForm()
	if request.method=='POST':
		form=UserCreationForm(request.POST)
		if form.is_valid():
			user=form.save(commit=False)
			#make the username a lower case os it wont be case sensitive to user. i.e even if you enter upper case or lower case username, it would be made lower and allow you in.
			user.username= user.username.lower()
			user.save()
			messages.success(request, 'Congratulation, registration successful!!!')
			#After registering, login the user in automatically
			login(request, user)
			return redirect('blogs:post')
		else:
			messages.error(request,'')
	context={ 'form':form}
	return render(request, 'blogs/login_register.html',context)




#Working Perfectly
def post(request):
	q=request.GET.get('q') if request.GET.get('q') !=None else''
	post=Article.objects.filter(headline__icontains=q)
	context={'post':post, }
	return render (request, 'blogs/index.html', context)




# def email_check(User): 
# 	return User.username.endswith('12g1')





#Working Perfectly
def updatecomment(request, pk):
	#called the Article object(id) so i can pass the id into the redirect link after the updating of the comment. i.e it would go back to that aricle page from where i clicked edit to the update page before
	# ss=Article.objects.get(pk=pk)
	detil=Comment.objects.get(pk=pk)
	#using this query(post) to back to the initial Article.
	post=detil.detil
	form=CommentForm(instance=detil)
	context={'form': form}
	if request.method =='POST':
		form=CommentForm(request.POST, instance=detil)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('blogs:post_detil', args=[str(post.pk)]))
	return render(request, 'blogs/post_detil.html', context)







#working perfectely
@login_required(login_url='blogs:login')
def replycomment(request, pk):
	detil=get_object_or_404(Comment, pk=pk)
	commentreply=detil.reply.all()
	new_reply=None
	if request.method == 'POST':
		comment_reply=CommentReply.objects.create(
			user=request.user,
			detil=detil,
			body=request.POST.get('body')
			)
		return HttpResponseRedirect(reverse('blogs:comment_reply', args=[str(detil.pk)]))

	else:
		form=ReplyForm()
	replycount=commentreply.count()
	context={'detil':detil, 'commentreply':commentreply,'new_reply':new_reply, 'form':form, 'replycount':replycount}
	return render(request, 'blogs/comment_reply.html', context)








# Working Perfectly
@login_required(login_url='blogs:login')
def deletecomment(request, pk):
	comment = get_object_or_404(Comment, pk=pk)
	post= comment.detil
	if request.method =='POST':
		comment.delete()
		return HttpResponseRedirect(reverse('blogs:post_detil', args=[post.pk, ]))
	context={'obj':comment}
	return render (request, 'blogs/delete.html', context)








#Working Perfectely
@login_required(login_url='blogs:login')
def deletereply(request, pk):
	del_reply=get_object_or_404(CommentReply, pk=pk)
	post=del_reply.detil
	if request.method=='POST':
		del_reply.delete()
		return HttpResponseRedirect(reverse('blogs:comment_reply', args=[post.pk, ]))
	context={'obj':del_reply}
	return render (request, 'blogs/delete.html', context)






# the update/edit reply view: The Changes are saving to the database, but the reverse is not returning to the comment reply pages i.e from where it came from 
def updatereply(request, pk):
	edit_reply=get_object_or_404(CommentReply, pk=pk)
	post=edit_reply.detil.pk
	form=ReplyForm(instance=edit_reply)
	if request.method=='POST':
		form=ReplyForm(request.POST,instance=edit_reply)
		if form.is_valid():
			form.save()
			print(edit_reply, edit_reply.pk)
			return redirect('blogs:comment_reply', pk=post)
			# return HttpResponseRedirect(redirect('blogs:comment_reply', args=[post]))
	context={'form': form, 'edit_reply':edit_reply, 'post':post}
	return render(request, 'blogs/edit_reply.html', context)








#Working perfectly
def about (request):
	return render(request, "blogs/about.html")


# @user_passes_test(email_check, login_url="blogs:login")
def post_detil (request, pk):
	post=Article.objects.all()
	detil=Article.objects.get(pk=pk)
	comments=detil.comments.all()
	comment=CommentForm(request.POST, request.FILES)
	# new_comment=None
	if request.method == 'POST':
		if comment.is_valid():
			if request.user.is_authenticated:
				comment=Comment.objects.create(
					user=request.user,
					detil=detil,
					body=request.POST.get('body'),
					comment_image=request.FILES.get('comment_image')
					)
			else:
				return redirect('blogs:login')
		
		return HttpResponseRedirect(reverse('blogs:post_detil', args=[str(detil.pk)]))
	else:
		form=CommentForm()
	#count the number of comments 
	count=comments.count()
	context={'count':count, 'detil':detil, 'post':post, 'comments':comments,'form':form}
	return render(request, 'blogs/post_detil.html',context)


# EduBlog Help Section
def roomMate(request):
	roommate=RoommateHelp.objects.all()
	form=RoommateHelpForm(request.POST, request.FILES)
	if request.method=='POST':
		form=RoommateHelp.objects.create(
			user=request.user,
			message=request.POST.get('message'),
			
			)
		return redirect('blogs:Edu-help')
	context={'roommate':roommate, 'form':form, }
	return render( request, 'blogs/roommate-help.html', context)

def roommateDelete(request, pk):
	roommatepost=RoommateHelp.objects.get(pk=pk)
	if request.method=='POST':
		roommatepost.delete()
		messages.success(request, 'Post deleted successful!!!')
		return redirect('blogs:Edu-help')
	context={'obj':roommatepost}
	return render (request, 'blogs/delete.html',context)

def editroommatePost(request, pk):
	roommatepost=RoommateHelp.objects.get(pk=pk)
	form=RoommateHelpForm(instance=roommatepost)
	if request.method=='POST':
		form=RoommateHelpForm(request.POST,instance=roommatepost)
		if form.is_valid():
			form.save()
			return redirect('blogs:Edu-help')
	context={'form':form}
	return render(request, 'blogs/roommate-help.html', context)

def carousel(request):
	slidedata=Carousel.objects.all()[0]
	context={'slide':slidedata}
	return render (request, 'blogs/carousel.html', context)


def contact(request):
	if request.method=='POST':
		message=request.POST['message']
		send_mail(
			'ContactForm',
			message,
			settings.EMAIL_HOST_USER,
			['nwaforglory6@gmail.com'],
			fail_silently=False
			)
	return render(request, 'blogs/index.html')



class MarkeTemplateView(TemplateView):

	template_name='blogs/market.html'
	model=Market
	
	

	def get(self,request, *args, **kwargs):
		q=request.GET.get('q') if request.GET.get('q') !=None else ''
		# products=Market.objects.all()[:3]
		products=Market.objects.filter(product_name__icontains=q)
		return render (request, self.template_name, {'products':products})






class MarketDetailView(DetailView):

	model=Market
	template_name='blogs/market_detail.html'
	context_object_name='product'



class MarketCreationForm(CreateView):
	form_class= SellForm
	template_name='blogs/sell_form.html'
	success_url='/products/'

	def post (self, request, *args, **kwargs):
		form=SellForm(request.POST, request.FILES)
		if form.is_valid():
			form.instance.user=self.request.user
			form.save()
			return redirect (self.success_url)
		return render(request, self.template_name, {'form': form})

class MarketUpdateview(UpdateView):
	model=Market
	form_class=SellForm
	template_name='blogs/sell_form.html'
	success_url='/products/'

class Marketdeleteview(DeleteView):
	model=Market
	form_class=SellForm
	template_name='blogs/delete.html'
	success_url='/products/'





#




	

































	# def form_valid(self, form):
	# 	form.instance.user = self.request.user
	# 	form.instance.product_image= self.request.FILES.get('product_image')

	# 	form.save()
			
	# 	return super().form_valid(form)

blogs/templates/blogs/comment_reply.html
{% extends 'base.html'%}
{% load static%}
{% load crispy_forms_tags%}
{%block content%}
<div class="container-fluid">
	<h3><span class="glyphicon glyphicon-user"></span>{{detil.user}}</h3>
	<p>{{detil.body}}</p><hr>
	<h4>Replies <span class="badge">{{replycount}}</span></h4>
	<div class="jumbotron" style="width: 50%;">
		{% for reply in commentreply%}

				<h4><span class="glyphicon glyphicon-user"></span> {{reply.user}}</h4>
				<p>{{reply.body}}</p>
				{% if request.user == reply.user%}
					<!-- <div  style="width:10%; margin-bottom: 10px;"> -->
						  <a href="{%url 'blogs:update_reply' reply.pk%}" class="btn btn-primary">Edit Reply</a>
						  <a href="{%url 'blogs:delete_reply' reply.pk%}" class="btn btn-primary">Delete</a>
						  
					<!-- </div> -->
				{% endif%}

		{% endfor%}
	
	</div>
		<form method="post" style="width:50%; margin-bottom: 10px;">
			{% csrf_token%}
			{{form.body}}
			<button class="btn btn-info btn-sm" id="submitButton" type="submit" style=" margin-top: 10px;">Post Comment</button>
		
		</form>
</div>
							
{% endblock%}

blogs/templates/blogs/delete.html
{% extends 'base.html'%}
{% load static %}
{% block content%}

<div class="container" style="margin-bottom: 10px;">
	<form method="POST">
		
		{%csrf_token%}
		<p> Are you sure you want to delete "<span class="text-danger">{{obj}}</span>"?</p>
		<a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary btn-sm">Go back</a>
		<input type="submit" value="Confirm" class="btn btn-primary btn-sm">

	</form>
</div>
{% endblock%}

blogs/templates/blogs/market.html
{% extends 'base.html'%}
{% block content%}

<style>
	.price{
		background-color: red;
		color: white;
		font-size: 10px;
		/*width: 30%;*/
		margin-top: 10px;
		width: 10%;
	}
	.category{
		font-size: 10px;
		background-color: yellow;
		color: black;
		margin-top: 10px;
		width: 10%;

	}
	.col-sm-2 img:hover{
		box-shadow:0 0 20px rgba(0, 0, 0, 0.3) ;
		transition: 0.5s;
	}
</style>

<div class="container">
	<h1 >Shopping Mall</h1>
	<!-- <form method="GET">
		<button ><input type="text" name="q" ><span class="glyphicon glyphicon-search"></span></button>
		
	</form> -->
	 <form method="GET"  accept-charset="UTF-8" style="width:50%;">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="search for products...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="submit"><span class="glyphicon glyphicon-search"></span></button>
              </span>
            </div>
          </form>
	 <hr>
	<div class="row " style="margin-bottom:10px;">
		{%for product in products%}
		<div >
			<h3>{{product.product_name}}</h3>
			{% if product.product_image %}
			<a href="{%url 'blogs:product-detail' product.pk%}" ><img src="{{product.product_image.url}}" class="img-thumbnail" alt="product image" width="100" height="100"></a>
			<p class="category">Category: {{product.category}}</p>
			<p class="price">Price: #{{product.product_price}}</p>
			<div class="btn-group">
			  <button type="button" class="btn btn-primary"><a href="{{product.product_image.url}}" style="color:white;">Full Image here</a> </button>
			  {%if request.user == product.user%}
			  <button type="button" class="btn btn-primary"><a href="{% url 'blogs:products' product.pk%}"style="color:white;">Edit</a></button>
			  <button type="button" class="btn btn-primary"><a href="{% url 'blogs:del-products' product.pk%}"style="color:white;">Delete</a></button>
			  {%endif%}
			</div>
			<!-- <a href="{{product.product_image.url}}" class="btn btn-xs btn-default">Full Image here</a>  -->
			<!-- {%if request.user == product.user%}
			<a href="{% url 'blogs:products' product.pk%}"class="btn btn-xs btn-primary">Edit</a><a href="{% url 'blogs:del-products' product.pk%}">Delete</a>
			{%endif%} -->
			{%else%}
			<p class="category">Category: {{product.category}}</p>
			<p class="price">Price: #{{product.product_price}}</p>
			<a href="" class="btn btn-xs btn-default">Full Image here</a>
			{%endif%}
		</div><hr>
		
		{%endfor%}

	</div>
</div>

	<!-- <div class="pagination"> <span class="step-links"> 
			{% if page_obj.has_previous %}
			<a href="?page={{ page_obj.previous_page_number }}"><span class="	glyphicon glyphicon-arrow-left"></span></a>
			{% endif %}
			<span class="current"> Page {{ page_obj.number }} of {{ paginator.num_pages }}. </span>
			{% if page_obj.has_next %}
				<a href="?page={{ page_obj.next_page_number }}"> <span class="	glyphicon glyphicon-arrow-right"></span></a> 
			{% endif %} </span> 
		</div>
	
</div> -->


<!-- {{product.user}}<br><hr>
{{product.category}}<br><hr>
 -->




{% endblock content%}

<!--  -->

blogs/templates/blogs/post_detil.html
{% extends 'base.html'%}
{% load static%}
{% load crispy_forms_tags%}
{%block content%}

    <div class="container">
   <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading"><h1>{{detil.headline}}</h1></div>
    </div>
     <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>Author: {{detil.reporter}}<br>
            <p>Posted: {{detil.pub_date|timesince}}</p>
            <p>{{detil.institution_website|safe}}| {{detil.institution_acronmy}}</p>
          </p><hr>
          {% if detil.post_image%}
          <p><img src="{{detil.image_url}}" style="width:70%; heiht:50%;"></p>
          <p>{{detil.content|safe}}</p>
          {%else%}
          <!-- <p><img src="{{detil.image_url.url}}" style="width:70%; heiht:50%;"></p> -->
          <p>{{detil.content|safe}}</p>
          {%endif%}
          <!-- comments to post -->
            <div class="container-fluid bg-ilnfo">
                  <h3>Leave a comment</h3>
                   <h4>Comments <span class="badge">{{count}}</span></h4>
                    <div class="jumbootron">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token%}
                            {{form}}
                          <button type="submit" class="btn btn-default btn-xs" style="margin-top:10px;">Post Comment</button>
                      </form>
                       {% for comment in comments%}
                       {% if comment.comment_image%}
                        <p style="margin-top:10px;"><span class="glyphicon glyphicon-user"></span> {{comment.user}}</p>
                        <p>{{comment.body}} </p>
                        <p><img src="{{comment.comment_image.url}}" alt="comment-img"></p>
                        {%else%}
                        <p style="margin-top:10px;"><span class="glyphicon glyphicon-user"></span> {{comment.user}}</p>
                        <p>{{comment.body}} </p>
                        {%endif%}
                        {% if request.user == comment.user%}
                          <a href="{% url 'blogs:update_detil' comment.pk %}" class="btn btn-sm  btn-default btn-xs">Edit comment</a>
                           <span><a href="{% url 'blogs:delete_comment' comment.pk%}" class="btn btn-sm btn-default btn-xs">Delete</a></span>
                           <span><a href="{% url 'blogs:comment_reply' comment.pk%}" class="btn btn-sm btn-default btn-xs">Reply</a></span>
                        {% else%}
                            <span><a href="{% url 'blogs:comment_reply' comment.pk%}" class="btn btn-sm btn-default btn-xs">Reply</a> </span>
                        {% endif%}
                              <br><br>
                              <!-- Reply section -->
                              <div class="row" style="margin-bottom: 10px;">

                                <h4><a href="{% url 'blogs:comment_reply' comment.pk%}" class="btn btn-default btn-xs">View Replies</a></h4>
                              </div>
                            <!--End of Reply Section  -->
                        {%empty%} 
                                <p>Be the first to comment</p>
                        {% endfor%}
                    </div>
                  </div>
          <!-- End of comments to posts -->
        </div>
        <div class="panel-footer">Panel Footer</div>
     </div> 
     </div>
     <div class="col-md-3">
       <div class="panel panel-default">
         <div class="panel-heading text-center"><h4>Related Posts</h4></div>
          <div class="panel-body">
            {%for post in post%}
            <p>
              <a href="">{{post.headline}}</a>
            </p><hr>
            {%endfor%}
            
          </div>
          <div class="panel-footer"><h6>Place order</h6></div>
       </div>
     </div>
   </div>
 </div>

 























      
{%endblock%}

blogs/templates/blogs/roommate-help.html
{% extends 'base.html'%}
{% load static%}
{% load crispy_forms_tags%}
{% block content%}
<style>
	.rough-div{
		background-color: grey;
		padding: 10px;
		color: white;
		border-radius: 1rem;
		margin-bottom: 10px;
	}
</style>

<div class="container-fluid">
	<h2 class="text-center text-danger">EduBlog Help Desk <span class="glyphicon glyphicon-phone"></span></h2> <hr>
	<div class="rough-div text-center">
		<h5>How to make a most on EduBlog Help Box follow the steps below</h5>
			<p>Step 1: Resigiter as a User, you can skip step 1 if you are a registerd user</p>
			<p> Step 2: Write using the message box bellow.</p>
			<p>Step 3: Make your description or message comprehensive so others can understand.</p>
			<p>Step 4: Click Post Message to post your message.</p>
			<p>Note: The charater limit is 1000</p>
	</div>
	<div class="row">
		<div class="col-sm-6" style="background-color: wheat; margin-bottom: 10px;">
			<h3>Need a roommate <span class="glyphicon glyphicon-question-sign"></span> Use the Helpbox</h3>
			<div class="container-fluid">
				<div class="row">
					<div class="col-sm-12">
						<h5 class="text-center">Help Box</h5>
						<div class=" text-center">
							<form method="POST">
								{% csrf_token%}
								{{form.message}}<br>
								{{form.help_file}}<br>
								<button type="submit" class="btn btn-sm btn-primary" style="margin-top: 10px; margin-bottom: 10px;">Post Message</button>
							</form>
							<!-- display posts -->
							<div class="rough-div" style="width: auto;">
								{% for post in roommate%}
								<div style="padding: 10px;">
									<h4><span class="glyphicon glyphicon-user"></span> {{post.user}}  <span class="badge"> {{post.created|timesince}}</h4>
									<p>{{post.message}}</span></p>
									{%if post.help_file%}
									<p><img src="{{post.help_file.url}}"></p><hr>
									{%endif%}}
									{% if request.user == post.user%}
									<a href="{% url 'blogs:Edu-help-edit' post.id%}" class="btn btn-primary btn-sm">Edit Post</a>
									<a href="{% url 'blogs:Edu-help-del' post.id%}" class="btn btn-primary btn-sm">Delete Post</a>
									{% endif%}
								</div>
								{% endfor%}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-6 panel panel-default" style="padding-left: 40px;">
				<div class="panel-heading"><h4>Are You in search of Accommodation <span class="glyphicon glyphicon-question-sign"><span class="glyphicon glyphicon-question-sign"><span class="glyphicon glyphicon-question-sign"></h4></div>
					<div class="panel-body ">
						<p>EduBlog has many empty lodges around ifite in and oustside the school with:
							<ul>
								<li>Running water</li>
								<li>Steady Light</li>
								<li>Security</li>
								<li>And very close to school</li>
							</ul>
						</p>
					</div>
				    <div class="panel-footer"><p>Contact EduBlog Accomodation management for acccomodation help around Unizik @ 07025065702</p></div>
				</div>
				<div class="col-sm-6" style="padding-left:40px;">
						<div class="rough-div ">
							<h3>Get all Unizik past-questions</h3>
								<ul>
									<li>Post Utme PastQuestion</li>
									<li>Undergraduate Past-question</li>
								</ul>
							<p>Note: We can deliver it to you inrespective of your location</p>
							<p>Contact EduBlog Help Desk around Unizik @ 07025065702</p>
						</div>
				</div>
			</div>
	</div>
</div>

{% endblock%}