Blog/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from .import views
from .views import *
from django.urls import path 
from django.contrib.auth.decorators import login_required
app_name = 'blogs'
urlpatterns = [
    
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),

    path('', views.post, name='post'),
    # path('footer/', views.footerDisplay, name='footer'),
    path('about/', views.about, name='about'),
    path('post_detil/<str:pk>/', views.post_detil, name='post_detil'),
    path('update_detil/<str:pk>/', views.updatecomment, name='update_detil'),
    path('comment_reply/<str:pk>/', views.replycomment, name='comment_reply'),
    path('delete_comment/<str:pk>/', views.deletecomment, name='delete_comment'),
    path('delete_reply/<str:pk>/', views.deletereply, name='delete_reply'),
    path('update_reply/<str:pk>/', views.updatereply, name='update_reply'),
    # Help section urls
    path('Edu-help/', views.roomMate, name='Edu-help'),
    path('Edu-help-del/<str:pk>/', views.roommateDelete, name='Edu-help-del'),
    path('Edu-help-edit/<str:pk>/', views.editroommatePost, name='Edu-help-edit'),
    # Advertisment Urls
    path('carousel/', views.carousel, name='carousel'),

    # class based classes url
    # path('products/', MarketListView.as_view(), name='products'),
    path('products/', MarkeTemplateView.as_view(), name='products'),
    path('products/<int:pk>/', MarketUpdateview.as_view(),  name='products'),
    path('del-products/<int:pk>/', Marketdeleteview.as_view(),  name='del-products'),
    path('product/<int:pk>/', MarketDetailView.as_view(), name='product-detail'), 
    path('buy-form/', MarketCreationForm.as_view(),  name='buy-form'),  
    # path('buy-form/', views.MarketCreationForm, name='buy-form'), 
    

 ]

templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <!-- bootstrap 4 -->
    
    <!-- end of bootstrap 4 -->
     <style>
    /* Set black background color, white text and some padding */
      #logo{
      background-color: #b70c01;
    }
    #footer{
      background-color: #b70c01;

    }
    #footer h5{
      color: white;
    }
    #footer p{
      color: whitesmoke;
    }

  body {
      position: relative; 
  }

  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }

  .explore a{
    color: white;
  }
  .explore ul {
    list-style: none;
    padding: 0;
  }
  </style>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50">

  <div id="header">
   <div id="logo">
     <div class="container">
       <div class="row align-item-center py-3" style="margin-top: 10px;">
         <div class="col-lg-3 col-md-4 col-sm-5 mb-sm-0 mb-2">
           <div class="logo text-sm-left text-center">
             <a href="/"><img src="{% static 'blogs/images/er.png'%}" class="img-fluid" style="width:50%; margin-bottom: 10px;"></a>
           </div>
         </div>
         <div class="col-lg-6 col-md-8 col-sm-7">
           <form method="GET" action="{% url 'blogs:post'%}" accept-charset="UTF-8">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Enter your search keywords here...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="submit"><span class="glyphicon glyphicon-search"></span></button>
              </span>
            </div>
          </form>
         </div>
         <div class="col-lg-3 text-right ">
          <div>
            {% if request.user.is_authenticated %}
            <a class="btn  btn-xs disablled" style="color:white;">Welcome {{user.get_username}}</a>
           <a href="{% url 'blogs:logout'%}"class="btn btn-default btn-sm">Logout</a>
           {%else%}
           <a href="{% url 'blogs:login'%}"class="btn btn-default btn-sm">Login</a>
           <a href="{% url 'blogs:register'%}" class="btn btn-default btn-sm">Sign Up</a>
           {% endif%}
           </div>
           </div>
         </div>
       </div>
     </div>
     <!-- Second Nav bar -->
     <nav class="navbar navbar-inverse " style="background-color:#830000; border: none; margin-left: -10px; margin-right: -10px;">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <div class="container dropdown" style="margin-right:10px;">
            <ul class="nav navbar-nav" >
              <li><a href="/" >Home</a></li>
              <li><a href="{% url 'blogs:about'%}" >About</a></li>
              <li><a href="{% url 'blogs:Edu-help'%}">Help</a></li>
              <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Universities <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#section1">Federal</a></li>
                  <li class="divider"></li>
                  <li><a a href="#section2">State</a></li>
                  <li class="divider"></li>
                  <li><a href="#section3">Private</a></li>
                </ul>
            </li>
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Polytechnics<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a a href="#section5">Federal Polytechnics</a></li>
                  <li class="divider"></li>
                  <li><a a href="#section6">State Polytechnics</a></li>
                  <li class="divider"></li>
                  <li><a a href="#section7">Private Polytechnics</a></li>
                </ul>
            </li>
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Coolledge of Education<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a a href="#section8">Federal Colledges</a></li>
                  <li class="divider"></li>
                  <li><a a href="#section9">State Colledges</a></li>
                </ul>
            </li>
            <li><a href="#">post your Article</a>
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Scholarships<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a a href="#section10">International Scholarships</a></li>
                  <li class="divider"></li>
                  <li><a a href="#section11">National Schoarships</a></li>
                </ul>
            </li>
            <li><a href="#" >Advertise</a></li>
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Shopping Mall<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{%url 'blogs:products'%}">Buy Item</a></li>
                  <li class="divider"></li>
                  <li><a a href="{% url 'blogs:buy-form'%}">Sell Item</a></li>
                </ul>
            </li>
          </div>
        </div>
      </div>
    </nav> 
    <!-- end of second nav bar -->
   </div>
 </div> 


  
    {% if messages %}
    <div class="alert alert-success">
      <ul class="messages"> 
        {% for message in messages %}
         <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
         <strong>{{ message }}</strong>
        <!-- <li>{{ message }}</li> -->
         {% endfor %} 
       </ul>
     </div> 
     {% endif %}
  

   {% block content%} {% endblock content%}

  <!-- Footer started here -->
  <div class="container-fluid" id="footer">
      <div class="row">
        <div class="container">
        <div class="col-sm-3">
          <h5>Welcome to EduBlog</h5><hr>
          <p>Yes! We are Nigeria's No1 Students' and Educational Resource Website</p><br><br><br>
          Join us on EduBlog <br>
          <a href="#" class="btn btn-success">Register</a>
          <p><a href="">Privacy Policy</a></p>
          <p><a href="">Terms of Use</a></p>
        </div>
        <div class="col-sm-3 explore">
          <h5>Quick Links</h5><hr>
          {%for post in footerDisplay%}
          <ul class="unstyle">
            <li><a href="{% url 'blogs:post_detil' post.pk%}">{{post}}</a></li>
          </ul>
          {%endfor%}
        </div>
        <div class="col-sm-3"><h5>Explore</h5><hr></div>
        <div class="col-sm-3"><h5>Connect with us</h5><hr>
          <div>
          <form method="POST">
            {%csrf_token%}
            <textarea name="message" placeholder="Enter your message......" class="form-control"> </textarea><br>
            <input type="submit" >
          </form>
          </div>  

        </div>
      </div>
    </div>
    {% if request.user.is_authenticated %}
    <p >You are logged in as {{user.first_name}}</p>
    {%endif%}
  </div>

<!-- Footer ended here -->
      
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Index Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <style>
    #logo{
      background-color: #b70c01;
    }
    #footer{
      background-color: #b70c01;

    }
    #footer h5{
      color: white;
    }
    #footer p{
      color: whitesmoke;
    }
    .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 100%;
      margin: auto;
  }
  </style>
</head>
<body>

 <div id="header">
   <div id="logo">
     <div class="container">
       <div class="row align-item-center py-3" style="margin-top: 10px;">
         <div class="col-lg-3 col-md-4 col-sm-5 mb-sm-0 mb-2">
           <div class="logo text-sm-left text-center">
             <a href="/"><img src="images/er.png" class="img-fluid" style="width:50%; margin-bottom: 10px;"></a>
           </div>
         </div>
         <div class="col-lg-6 col-md-8 col-sm-7">
           <form method="GET" action="https://myschool.ng/search" accept-charset="UTF-8">
            <div class="input-group">
              <input type="text" name="search_string" class="form-control" placeholder="Enter your search keywords here...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="submit"><span class="glyphicon glyphicon-search"></span></button>
              </span>
            </div>
          </form>
         </div>
         <div class="col-lg-3 text-right ">
          <div>
           <a href="#" class="btn btn-default btn-sm">Register</a>
           <a href="#"class="btn btn-default btn-sm">Login</a>
           </div>
           </div>
         </div>
       </div>
     </div>
     <!-- Second Nav bar -->
     <nav class="navbar navbar-inverse" style="background-color:#830000; border: none; margin-left: -10px; margin-right: -10px;">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <div class="container" style="margin-right:10px;">
            <ul class="nav navbar-nav" >
              <li><a href="#">Home</a></li>
              <li><a href="#">Page 1</a></li>
              <li><a href="#">Page 2</a></li>
              <li><a href="#">Page 3</a></li>
              <li><a href="#">Page 4</a></li>
              <li><a href="#">Page 5</a></li>
              <li><a href="#">Page 6</a></li>
              <li><a href="#">Page 7</a></li>
              <li><a href="#">Page 8</a></li>
              <li><a href="#">Page 9</a></li>
              <li><a href="#">Page 10</a></li>
              <li><a href="#">Page 11</a></li>
              <li><a href="#">Page 12</a></li>
            </ul>
            </ul>
          </div>
        </div>
      </div>
    </nav> 
    <!-- end of second nav bar -->
   </div>
 </div>

 <!-- Carousel Section -->
 <div class="container">
   <div class="container-fluid" style="margin-bottom: 30px; ">
        <br>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="container">
            <h3 class="text-center">Advertise your Business with Us</h3>
          <div class="carousel-inner" role="listbox">
            <div class="item active ">
              <img src="images/blackwoman.jpg" alt="Chania" width="460" height="345" style="height: 300px;">
            </div>

            <div class="item">
              <img src="images/cake3.jpg" alt="Chania" width="460" height="345" style="height: 300px;">
            </div>
          
            <div class="item">
              <img src="images/cake1.jpg" alt="Flower" width="460" height="345" style="height: 300px;">
            </div>

            <div class="item">
              <img src="images/cake2.jpg" alt="Flower" width="460" height="345" style="height: 300px;">
            </div>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
  </div>
 <!-- End of Carousel -->

 <div class="container"style="margin-bottom: 10px;">
   <div class="row">
    <h3 class="text-center">News Updates</h3><hr>
     <div class="col-sm-4">
      <h5>Latest University News</h5><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
     </div>
     <div class="col-sm-4">
       <h5>Latest Academic News</h5><hr>
       <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
     </div>
     <div class="col-sm-4">
        <h5>Latest Polytechnic News</h5><hr>
       <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
      <p> KWASU admitted candidates with incomplete registration status, 2021/2022</p><hr>
     </div>
   </div>
 </div>

</div>
<!--  End of Schhol News -->

<!-- Besfining of scholarship news -->
<div class="container">
  <div class="row">
    <h3 class="text-center">Scholarships for Nigerian Students</h3><hr>
    <div class="col-sm-4">
        <h5>International Scholarships</h5><hr>
        <p>Presidential Scholarships at Alvernia University, USA - 2022</p><hr>
        <p>Presidential Scholarships at Alvernia University, USA - 2022</p><hr>
        <p>Presidential Scholarships at Alvernia University, USA - 2022</p><hr>
        <p>Presidential Scholarships at Alvernia University, USA - 2022</p><hr>
    </div>
    <div class="col-sm-4">
        <h5>Local Scholarships</h5><hr>
        <p>Presidential Scholarships at Alvernia University, USA - 2022</p><hr>
        <p>Presidential Scholarships at Alvernia University, USA - 2022</p><hr>
        <p>Presidential Scholarships at Alvernia University, USA - 2022</p><hr>
        <p>Presidential Scholarships at Alvernia University, USA - 2022</p><hr>
    </div>
    <div class="col-sm-4">
        <h5>All Scholarships</h5><hr>
        <p>Presidential Scholarships at Alvernia University, USA - 2022</p><hr>
        <p>Presidential Scholarships at Alvernia University, USA - 2022</p><hr>
        <p>Presidential Scholarships at Alvernia University, USA - 2022</p><hr>
        <p>Presidential Scholarships at Alvernia University, USA - 2022</p><hr>
    </div>
  </div>
</div>
<!-- End of scholarship News -->

<!-- Footer started here -->
  <div class="container-fluid" id="footer">
      <div class="row">
        <div class="container">
        <div class="col-sm-3">
          <h5>Welcome to EduBlog</h5><hr>
          <p>Yes! We are Nigeria's No1 Students' and Educational Resource Website</p><br><br><br>
          Join us on EduBlog <br>
          <a href="#" class="btn btn-success">Register</a>
          <p><a href="">Privacy Policy</a></p>
          <p><a href="">Terms of Use</a></p>
        </div>
        <div class="col-sm-3">
          <h5>Explore</h5><hr></div>
        <div class="col-sm-3"><h5>Quick Links</h5><hr></div>
        <div class="col-sm-3"><h5>Connect with us</h5><hr></div>
      </div>
    </div>
  </div>
<!-- Footer ended here -->
</body>
</html> 

templates/login_register.html
{% extends 'base.html'%}
{% load crispy_forms_tags%}
{% block content%}

		{% if page == 'login' %}
			<div class="container" style="width: 30%;">
				<div class="jumbotron">
				<form method="POST">
					{% csrf_token%}
					
					<div class="mb-3 mt-3">
					    <label for="username" class="form-label">Username:</label>
					    <input type="username" class="form-control" id="username" placeholder="Enter username" name="username">
		  			</div>

					<div class="mb-3">
					    <label for="pwd" class="form-label">Password:</label>
					    <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd">
		  			</div>

					<input type="submit" value=" Login"class="btn btn-primary" style="margin-top:10px;" >
					<!-- <button type="submit" class="btn btn-primary" style="margin-top:10px;">Login</button> -->
					
				</form><br><br>
				<p>Haven't signed up yet?</p>
				<a href="{% url 'blogs:register'%}" class="btn btn-primary">Sign up</a>
				</div>	
			</div>

		{%else%}
			<div class="container" style="width: 40%;">
				<div class="jumbotron">
					<form method="POST">
						{% csrf_token%}
						{{form|crispy}}
						<input type="submit" value="Register" class="btn btn-primary">
						
					</form><br>
					<p>Already signed up?</p>
					<a href="{% url 'blogs:login'%}" class="btn btn-primary" style="margin-bottom: 10px;">Login</a>
						
				</div>
			</div>
		{% endif%}

{% endblock%}

templates/ss.html
<body>
	
</body>